import { Image, Pressable, ScrollView, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { CalendarLine } from "../../assets/icons/CalendarLine";
import { ClockLine } from "../../assets/icons/ClockLine";
import { Dash } from "../../assets/icons/Dash";
import { Option } from "../../assets/icons/Option";
import { colorPrimitives } from "../../constants/theme";
import { lightModeStyles } from "../../styles/theme/light";
import { utilityStyles } from "../../styles/utility";

function ScheduleScreen() {
  const userImage = require("../../assets/images/user.jpg");
  return (
    <>
      <SafeAreaView
        style={[
          utilityStyles.flex1,
          utilityStyles.flexCol,
          utilityStyles.gMd,
          {
            backgroundColor: "#fff",
          },
        ]}
      >
        <ScrollView>
          <View
            style={[
              utilityStyles.flex1,
              utilityStyles.flexCol,
              utilityStyles.gMd,
              { paddingInline: 20, paddingTop: 10 },
            ]}
          >
            <View
              style={[
                utilityStyles.flexRow,
                utilityStyles.alignCenter,
                utilityStyles.justifyBetween,
              ]}
            >
              <Text
                style={[
                  utilityStyles.text4Xl,
                  utilityStyles.fontBold,
                  lightModeStyles.textLight,
                ]}
              >
                Schedule
              </Text>
              <Pressable
                style={[
                  lightModeStyles.bgLight,
                  utilityStyles.flexRow,
                  utilityStyles.gXs,
                  utilityStyles.roundedCircle,
                  { padding: 16 },
                ]}
              >
                <View>
                  <CalendarLine
                    width={16}
                    height={16}
                    color={colorPrimitives.light.colorTextPrimary}
                  />
                </View>
                <Text
                  style={[
                    utilityStyles.fontMedium,
                    utilityStyles.textXs,
                    lightModeStyles.textLight,
                  ]}
                >
                  January 2025
                </Text>
              </Pressable>
            </View>
            <View style={{ height: 55 }}>
              <ScrollView
                horizontal={true}
                contentContainerStyle={{ columnGap: 8, height: 55 }}
              >
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.bgPrimary,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    { width: 45, height: 55 },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.colorOnPrimary,
                    ]}
                  >
                    Mon
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.colorOnPrimary,
                    ]}
                  >
                    17
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Tue
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    18
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Wed
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    19
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Thur
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    20
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Fri
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    21
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Sat
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    22
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Sun
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    23
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Mon
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    24
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Tue
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    25
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Wed
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    25
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Thur
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    18
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Tue
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    18
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Tue
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    18
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Tue
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    18
                  </Text>
                </Pressable>
                <Pressable
                  style={[
                    utilityStyles.pXs,
                    utilityStyles.flexCol,
                    utilityStyles.gXs,
                    lightModeStyles.borderColor,
                    utilityStyles.alignCenter,
                    utilityStyles.roundedXl,
                    {
                      width: 45,
                      height: 55,
                      backgroundColor: "#fff",
                      borderWidth: 0.5,
                    },
                  ]}
                >
                  <Text
                    style={[
                      utilityStyles.fontMedium,
                      utilityStyles.text2Xs,
                      lightModeStyles.textLight,
                    ]}
                  >
                    Tue
                  </Text>
                  <Text
                    style={[
                      utilityStyles.textXs,
                      utilityStyles.fontBold,
                      lightModeStyles.textLight,
                    ]}
                  >
                    18
                  </Text>
                </Pressable>
              </ScrollView>
            </View>
            <Text
              style={[
                utilityStyles.textMd,
                utilityStyles.fontBold,
                lightModeStyles.textLight,
              ]}
            >
              First Semester Timetable
            </Text>
            <View style={[utilityStyles.flexCol, utilityStyles.gSm]}>
              <View
                style={[
                  utilityStyles.roundedXl,
                  utilityStyles.pMd,
                  lightModeStyles.borderColor,
                  utilityStyles.flexCol,
                  utilityStyles.gMd,
                  { backgroundColor: "#fff", borderWidth: 0.5 },
                ]}
              >
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.justifyBetween,
                    utilityStyles.w100,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textMd,
                      utilityStyles.fontSemiBold,
                    ]}
                  >
                    Engineering Mathematics
                  </Text>
                  <View>
                    <Option
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    SWE001
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    3 Credit
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.alignCenter,
                    utilityStyles.gXs,
                  ]}
                >
                  <Image
                    source={userImage}
                    style={{ width: 35, height: 35, borderRadius: 5 }}
                  />
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    Dr. Alex Johnson
                  </Text>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                      { letterSpacing: 0.2, lineHeight: 20 },
                    ]}
                  >
                    Fundamentals of programming concepts using Python, including
                    variables, control structures, and basic algorithms...
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.g2Xs,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <View>
                    <ClockLine
                      width={16}
                      height={16}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    9:30 AM
                  </Text>
                  <View>
                    <Dash
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    11:00 AM,
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    2h 30Min
                  </Text>
                </View>
              </View>
              <View
                style={[
                  utilityStyles.roundedXl,
                  utilityStyles.pMd,
                  lightModeStyles.borderColor,
                  utilityStyles.flexCol,
                  utilityStyles.gMd,
                  { backgroundColor: "#fff", borderWidth: 0.5 },
                ]}
              >
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.justifyBetween,
                    utilityStyles.w100,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textMd,
                      utilityStyles.fontSemiBold,
                    ]}
                  >
                    Engineering Mathematics
                  </Text>
                  <View>
                    <Option
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    SWE001
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    3 Credit
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.alignCenter,
                    utilityStyles.gXs,
                  ]}
                >
                  <Image
                    source={userImage}
                    style={{ width: 35, height: 35, borderRadius: 5 }}
                  />
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    Dr. Alex Johnson
                  </Text>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                      { letterSpacing: 0.2, lineHeight: 20 },
                    ]}
                  >
                    Fundamentals of programming concepts using Python, including
                    variables, control structures, and basic algorithms...
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.g2Xs,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <View>
                    <ClockLine
                      width={16}
                      height={16}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    9:30 AM
                  </Text>
                  <View>
                    <Dash
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    11:00 AM,
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    2h 30Min
                  </Text>
                </View>
              </View>
              <View
                style={[
                  utilityStyles.roundedXl,
                  utilityStyles.pMd,
                  lightModeStyles.borderColor,
                  utilityStyles.flexCol,
                  utilityStyles.gMd,
                  { backgroundColor: "#fff", borderWidth: 0.5 },
                ]}
              >
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.justifyBetween,
                    utilityStyles.w100,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textMd,
                      utilityStyles.fontSemiBold,
                    ]}
                  >
                    Engineering Mathematics
                  </Text>
                  <View>
                    <Option
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    SWE001
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    3 Credit
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.alignCenter,
                    utilityStyles.gXs,
                  ]}
                >
                  <Image
                    source={userImage}
                    style={{ width: 35, height: 35, borderRadius: 5 }}
                  />
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    Dr. Alex Johnson
                  </Text>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                      { letterSpacing: 0.2, lineHeight: 20 },
                    ]}
                  >
                    Fundamentals of programming concepts using Python, including
                    variables, control structures, and basic algorithms...
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.g2Xs,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <View>
                    <ClockLine
                      width={16}
                      height={16}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    9:30 AM
                  </Text>
                  <View>
                    <Dash
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    11:00 AM,
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    2h 30Min
                  </Text>
                </View>
              </View>
              <View
                style={[
                  utilityStyles.roundedXl,
                  utilityStyles.pMd,
                  lightModeStyles.borderColor,
                  utilityStyles.flexCol,
                  utilityStyles.gMd,
                  { backgroundColor: "#fff", borderWidth: 0.5 },
                ]}
              >
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.justifyBetween,
                    utilityStyles.w100,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textMd,
                      utilityStyles.fontSemiBold,
                    ]}
                  >
                    Engineering Mathematics
                  </Text>
                  <View>
                    <Option
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    SWE001
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    3 Credit
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.alignCenter,
                    utilityStyles.gXs,
                  ]}
                >
                  <Image
                    source={userImage}
                    style={{ width: 35, height: 35, borderRadius: 5 }}
                  />
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    Dr. Alex Johnson
                  </Text>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                      { letterSpacing: 0.2, lineHeight: 20 },
                    ]}
                  >
                    Fundamentals of programming concepts using Python, including
                    variables, control structures, and basic algorithms...
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.g2Xs,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <View>
                    <ClockLine
                      width={16}
                      height={16}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    9:30 AM
                  </Text>
                  <View>
                    <Dash
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    11:00 AM,
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    2h 30Min
                  </Text>
                </View>
              </View>
              <View
                style={[
                  utilityStyles.roundedXl,
                  utilityStyles.pMd,
                  lightModeStyles.borderColor,
                  utilityStyles.flexCol,
                  utilityStyles.gMd,
                  { backgroundColor: "#fff", borderWidth: 0.5 },
                ]}
              >
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.justifyBetween,
                    utilityStyles.w100,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textMd,
                      utilityStyles.fontSemiBold,
                    ]}
                  >
                    Engineering Mathematics
                  </Text>
                  <View>
                    <Option
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    SWE001
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    3 Credit
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.alignCenter,
                    utilityStyles.gXs,
                  ]}
                >
                  <Image
                    source={userImage}
                    style={{ width: 35, height: 35, borderRadius: 5 }}
                  />
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    Dr. Alex Johnson
                  </Text>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                      { letterSpacing: 0.2, lineHeight: 20 },
                    ]}
                  >
                    Fundamentals of programming concepts using Python, including
                    variables, control structures, and basic algorithms...
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.g2Xs,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <View>
                    <ClockLine
                      width={16}
                      height={16}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    9:30 AM
                  </Text>
                  <View>
                    <Dash
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    11:00 AM,
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    2h 30Min
                  </Text>
                </View>
              </View>
              <View
                style={[
                  utilityStyles.roundedXl,
                  utilityStyles.pMd,
                  lightModeStyles.borderColor,
                  utilityStyles.flexCol,
                  utilityStyles.gMd,
                  { backgroundColor: "#fff", borderWidth: 0.5 },
                ]}
              >
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.justifyBetween,
                    utilityStyles.w100,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textMd,
                      utilityStyles.fontSemiBold,
                    ]}
                  >
                    Engineering Mathematics
                  </Text>
                  <View>
                    <Option
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    SWE001
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    3 Credit
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.alignCenter,
                    utilityStyles.gXs,
                  ]}
                >
                  <Image
                    source={userImage}
                    style={{ width: 35, height: 35, borderRadius: 5 }}
                  />
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    Dr. Alex Johnson
                  </Text>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                      { letterSpacing: 0.2, lineHeight: 20 },
                    ]}
                  >
                    Fundamentals of programming concepts using Python, including
                    variables, control structures, and basic algorithms...
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.g2Xs,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <View>
                    <ClockLine
                      width={16}
                      height={16}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    9:30 AM
                  </Text>
                  <View>
                    <Dash
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    11:00 AM,
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    2h 30Min
                  </Text>
                </View>
              </View>
              <View
                style={[
                  utilityStyles.roundedXl,
                  utilityStyles.pMd,
                  lightModeStyles.borderColor,
                  utilityStyles.flexCol,
                  utilityStyles.gMd,
                  { backgroundColor: "#fff", borderWidth: 0.5 },
                ]}
              >
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.justifyBetween,
                    utilityStyles.w100,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textMd,
                      utilityStyles.fontSemiBold,
                    ]}
                  >
                    Engineering Mathematics
                  </Text>
                  <View>
                    <Option
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    SWE001
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    3 Credit
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.alignCenter,
                    utilityStyles.gXs,
                  ]}
                >
                  <Image
                    source={userImage}
                    style={{ width: 35, height: 35, borderRadius: 5 }}
                  />
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    Dr. Alex Johnson
                  </Text>
                </View>
                <View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                      { letterSpacing: 0.2, lineHeight: 20 },
                    ]}
                  >
                    Fundamentals of programming concepts using Python, including
                    variables, control structures, and basic algorithms...
                  </Text>
                </View>
                <View
                  style={[
                    utilityStyles.flexRow,
                    utilityStyles.g2Xs,
                    utilityStyles.alignCenter,
                  ]}
                >
                  <View>
                    <ClockLine
                      width={16}
                      height={16}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    9:30 AM
                  </Text>
                  <View>
                    <Dash
                      width={20}
                      height={20}
                      color={colorPrimitives.light.colorTextPrimary}
                    />
                  </View>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    11:00 AM,
                  </Text>
                  <Text
                    style={[
                      lightModeStyles.textLight,
                      utilityStyles.textSm,
                      utilityStyles.fontMedium,
                    ]}
                  >
                    2h 30Min
                  </Text>
                </View>
              </View>
            </View>
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
}
export default ScheduleScreen;
